const { response } = require('express');
const mongodb = require('../data/database');
const ObjectId = require("mongodb").ObjectId;

const getAll = async (req, res) => {
  try {
    const result = await mongodb.getDatabase().db('project2').collection('houses').find().toArray();
    res.setHeader('Content-Type', 'application/json');
    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({ error: error.message || "An error occurred while retrieving all houses" });
  }
};

const getSingle = async (req, res) => {
  try {
    const HouseId = new ObjectId(req.params.id);
    const result = await mongodb.getDatabase().db('project2').collection('houses').findOne({ _id: HouseId });
    if (!result) {
      throw new Error("House not found");
    }
    res.setHeader('Content-Type', 'application/json');
    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({ error: error.message || "An error occurred while retrieving the house" });
  }
};

const createHouse = async (req, res) => {
  try {
    const house = {
      type: req.body.type,
      value: req.body.value,
      name: req.body.name,
    };
    const response = await mongodb.getDatabase().db('project2').collection('houses').insertOne(house);
    if (!response.acknowledged) {
      throw new Error("Failed to create the house");
    }
    res.status(201).json({ id: response.insertedId, message: "House created successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message || "An error occurred while creating the house" });
  }
};

const updateHouse = async (req, res) => {
  try {
    const HouseId = new ObjectId(req.params.id);
    const house = {
      type: req.body.type,
      value: req.body.value,
      name: req.body.name,
    };
    const response = await mongodb.getDatabase().db('project2').collection('houses').replaceOne({ _id: HouseId }, house);
    if (response.modifiedCount === 0) {
      throw new Error("House not found or no updates were made");
    }
    res.status(200).json({ message: "House updated successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message || "An error occurred while updating the house" });
  }
};

const deleteHouse = async (req, res) => {
  try {
    const HouseId = new ObjectId(req.params.id);
    const response = await mongodb.getDatabase().db('project2').collection('houses').deleteOne({ _id: HouseId });
    if (response.deletedCount === 0) {
      throw new Error("House not found");
    }
    res.status(200).json({ message: "House deleted successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message || "An error occurred while deleting the house" });
  }
};


module.exports = {
    getAll,
    getSingle,
    createHouse,
    updateHouse,
    deleteHouse
};